---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: false
configure_osx: false

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
 - TV
 - Podcasts
 - Launchpad
 - Music
 - Messages
 - Mail
 - Photos
dockitems_persist:
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 1
 - name: "Firefox"
   path: "/Applications/Firefox.app/"
   pos: 2
 - name: "iTerm"
   path: "/Applications/iTerm.app/"
   pos: 3


configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  - coreutils
  - diffutils
  - findutils
  - gawk
  - { name: gnu-sed, install_options: "default-names"}
  - { name: gnu-tar, install_options: "default-names"}
  - gzip
  - watch
  - rsync
  - ansible
  - bash-completion
  - git
  - gpg
  - nmap
  - ssh-copy-id
  - openssl
  - pv
  - wget
  - vim 
  - git-delta
  - zsh
  - zsh-syntax-highlighting
  - htop
  - fzf
  - bat
  - ripgrep
  - jq
  - watch
  - black
  - pyenv
  - pyenv-virtualenv
  - aria2
  - readline
  - sqlite3
  - xz
  - zlib
  - clintmod/formulas/macprefs
  - { name: vim, install_options: "with-luajit,override-system-vi" }
  - pgcli
  - awscli
  - node
  - mosh
  - MisterTea/et/et

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  # - docker
  # - docker-compose
  - firefox
  - slack
  - telegram
  - whatsapp
  - iterm2
  - visual-studio-code
  - maccy
  - numi
  - kap
  - inkscape
  - amethyst
  - google-drive
  - menumeters
  - coconutbattery
  - monodraw
  - krita
  - gimp
  - vlc
  - zoom
  - calibre
  - bartender
  - microsoft-edge
  - scummvm
  - github
  - gh
  - bitbar
  - postman

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 937984704, name: "Amphetamine" }
  - { id: 688211836, name: "EasyRes" }
  - { id: 1451462297, name: "MultiCam" }
  - { id: 595117824, name: "EpochTime" }

mas_email: ""
mas_password: ""

# osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
